# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


jobs:
- job: build
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    imageName: 'hellopython:$(build.buildId)'
    registerName: agogosacr.azurecr.io
    spName: '98a60d8a-cd03-44cb-9367-f19ab0d98b8d'
  steps:
  - script: docker build -f sampleapp/Dockerfile -t $(registerName)/$(imageName) .
    displayName: 'docker build'
  - script: |
      docker login $(registerName) -u $(spName) -p $(spPassword)
      docker push $(registerName)/$(imageName)
    displayName: 'push to acr'