replicaCount: 1

image:
  repository: agogosacr.azurecr.io/agogo-sample
  tag: v1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# base64 encoded test strings
env:
  AZURE_STORAGE_ACCOUNT: ""
  EVENT_HUB_CONSUMER_GROUP: ""
  AZURE_STORAGE_CONTAINER: ""
  AZURE_STORAGE_ACCESS_KEY: ""
  EVENT_HUB_NAMESPACE: ""
  EVENT_HUB_STORAGE_ACCOUNT: ""
  EVENT_HUB_STORAGE_CONTAINER: ""
  EVENT_HUB_NAME: ""
  EVENT_HUB_SAS_POLICY: ""
  EVENT_HUB_SAS_KEY: ""

service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
