# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: agogosacr.azurecr.io/agogo-sample
  tag: v1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# base64 encoded test strings
env:
  EH_CONN_STRING: ""
  BLOB_ST_CONN_STRING: ""
  BUILD_NAME: "" 
  AZURE_STORAGE_ACCOUNT: ""
  AZURE_STORAGE_ACCESS_KEY: ""
  EVENT_HUB_NAMESPACE: ""
  EVENT_HUB_NAME: ""
  EVENT_HUB_SAS_POLICY: ""
  EVENT_HUB_SAS_KEY: ""

service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
