apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: "EH_CONN_STRING"
              valueFrom: 
                secretKeyRef:
                  key: EH_CONN_STRING
                  name: {{ .Release.Name }}-auth
            - name: "BLOB_ST_CONN_STRING"
              valueFrom: 
                secretKeyRef:
                  key: BLOB_ST_CONN_STRING
                  name: {{ .Release.Name }}-auth
            - name: "BUILD_NAME"
              valueFrom: 
                secretKeyRef:
                  key: BUILD_NAME
                  name: {{ .Release.Name }}-auth
            - name: "AZURE_STORAGE_ACCOUNT"
              valueFrom: 
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT
                  name: {{ .Release.Name }}-auth
            - name: "AZURE_STORAGE_ACCESS_KEY"
              valueFrom: 
                secretKeyRef:
                  key: AZURE_STORAGE_ACCESS_KEY
                  name: {{ .Release.Name }}-auth
            - name: "EVENT_HUB_NAMESPACE"
              valueFrom: 
                secretKeyRef:
                  key: EVENT_HUB_NAMESPACE
                  name: {{ .Release.Name }}-auth
            - name: "EVENT_HUB_NAME"
              valueFrom: 
                secretKeyRef:
                  key: EVENT_HUB_NAME
                  name: {{ .Release.Name }}-auth
            - name: "EVENT_HUB_SAS_POLICY"
              valueFrom: 
                secretKeyRef:
                  key: EVENT_HUB_SAS_POLICY
                  name: {{ .Release.Name }}-auth
            - name: "EVENT_HUB_SAS_KEY"
              valueFrom: 
                secretKeyRef:
                  key: EVENT_HUB_SAS_KEY
                  name: {{ .Release.Name }}-auth
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
