apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.env.AZURE_STORAGE_ACCESS_KEY}}
  EVENT_HUB_SAS_KEY: {{ .Values.env.EVENT_HUB_SAS_KEY}}